export const CountryCodes = [
  { name: "United States", code: "US" },
  { name: "Canada", code: "CA" },
  { name: "United Kingdom", code: "GB" },
  { name: "Australia", code: "AU" },
  { name: "Germany", code: "DE" },
  { name: "France", code: "FR" },
  { name: "Japan", code: "JP" },
  { name: "China", code: "CN" },
  { name: "India", code: "IN" },
  { name: "Brazil", code: "BR" },
  { name: "Mexico", code: "MX" },
  { name: "Spain", code: "ES" },
  { name: "Italy", code: "IT" },
  { name: "Netherlands", code: "NL" },
  { name: "Sweden", code: "SE" },
  { name: "Norway", code: "NO" },
  { name: "Denmark", code: "DK" },
  { name: "Finland", code: "FI" },
  { name: "Switzerland", code: "CH" },
  { name: "Austria", code: "AT" },
  { name: "Belgium", code: "BE" },
  { name: "Poland", code: "PL" },
  { name: "Czech Republic", code: "CZ" },
  { name: "Hungary", code: "HU" },
  { name: "Portugal", code: "PT" },
  { name: "Greece", code: "GR" },
  { name: "Ireland", code: "IE" },
  { name: "New Zealand", code: "NZ" },
  { name: "South Korea", code: "KR" },
  { name: "Singapore", code: "SG" },
  { name: "Hong Kong", code: "HK" },
  { name: "Taiwan", code: "TW" },
  { name: "Thailand", code: "TH" },
  { name: "Malaysia", code: "MY" },
  { name: "Indonesia", code: "ID" },
  { name: "Philippines", code: "PH" },
  { name: "Vietnam", code: "VN" },
  { name: "South Africa", code: "ZA" },
  { name: "Egypt", code: "EG" },
  { name: "Nigeria", code: "NG" },
  { name: "Kenya", code: "KE" },
  { name: "Morocco", code: "MA" },
  { name: "Tunisia", code: "TN" },
  { name: "Algeria", code: "DZ" },
  { name: "Ghana", code: "GH" },
  { name: "Ethiopia", code: "ET" },
  { name: "Uganda", code: "UG" },
  { name: "Tanzania", code: "TZ" },
  { name: "Rwanda", code: "RW" },
  { name: "Argentina", code: "AR" },
  { name: "Chile", code: "CL" },
  { name: "Colombia", code: "CO" },
  { name: "Peru", code: "PE" },
  { name: "Venezuela", code: "VE" },
  { name: "Ecuador", code: "EC" },
  { name: "Bolivia", code: "BO" },
  { name: "Paraguay", code: "PY" },
  { name: "Uruguay", code: "UY" },
  { name: "Guyana", code: "GY" },
  { name: "Suriname", code: "SR" },
  { name: "Russia", code: "RU" },
  { name: "Ukraine", code: "UA" },
  { name: "Belarus", code: "BY" },
  { name: "Kazakhstan", code: "KZ" },
  { name: "Uzbekistan", code: "UZ" },
  { name: "Kyrgyzstan", code: "KG" },
  { name: "Tajikistan", code: "TJ" },
  { name: "Turkmenistan", code: "TM" },
  { name: "Azerbaijan", code: "AZ" },
  { name: "Armenia", code: "AM" },
  { name: "Georgia", code: "GE" },
  { name: "Moldova", code: "MD" },
  { name: "Romania", code: "RO" },
  { name: "Bulgaria", code: "BG" },
  { name: "Croatia", code: "HR" },
  { name: "Slovenia", code: "SI" },
  { name: "Slovakia", code: "SK" },
  { name: "Lithuania", code: "LT" },
  { name: "Latvia", code: "LV" },
  { name: "Estonia", code: "EE" },
  { name: "Iceland", code: "IS" },
  { name: "Luxembourg", code: "LU" },
  { name: "Malta", code: "MT" },
  { name: "Cyprus", code: "CY" },
  { name: "Israel", code: "IL" },
  { name: "Turkey", code: "TR" },
  { name: "Saudi Arabia", code: "SA" },
  { name: "United Arab Emirates", code: "AE" },
  { name: "Qatar", code: "QA" },
  { name: "Kuwait", code: "KW" },
  { name: "Bahrain", code: "BH" },
  { name: "Oman", code: "OM" },
  { name: "Jordan", code: "JO" },
  { name: "Lebanon", code: "LB" },
  { name: "Syria", code: "SY" },
  { name: "Iraq", code: "IQ" },
  { name: "Iran", code: "IR" },
  { name: "Afghanistan", code: "AF" },
  { name: "Pakistan", code: "PK" },
  { name: "Bangladesh", code: "BD" },
  { name: "Sri Lanka", code: "LK" },
  { name: "Nepal", code: "NP" },
  { name: "Bhutan", code: "BT" },
  { name: "Maldives", code: "MV" },
  { name: "Myanmar", code: "MM" },
  { name: "Cambodia", code: "KH" },
  { name: "Laos", code: "LA" },
  { name: "Brunei", code: "BN" },
  { name: "Mongolia", code: "MN" },
  { name: "North Korea", code: "KP" },
  { name: "Marshall Islands", code: "MH" },
  { name: "Micronesia", code: "FM" },
  { name: "Palau", code: "PW" },
  { name: "Fiji", code: "FJ" },
  { name: "Papua New Guinea", code: "PG" },
  { name: "Solomon Islands", code: "SB" },
  { name: "Vanuatu", code: "VU" },
  { name: "Samoa", code: "WS" },
  { name: "Tonga", code: "TO" },
  { name: "Kiribati", code: "KI" },
  { name: "Tuvalu", code: "TV" },
  { name: "Nauru", code: "NR" },
];
